GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/salkfj

###

DELETE http://localhost:3001/api/persons/632857a0a844bac892e29f0a

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test",
    "number": "1234"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "1234"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test"
}
